[package]
name = "auction-circuit-program"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-zkvm = "5.0"
sha2 = { version = "0.10", default-features = false }
borsh = { version = "1.0", features = ["derive"], default-features = false }
